ALTER TABLE days ADD COLUMN video1_url TEXT NOT NULL DEFAULT '';
ALTER TABLE days ADD COLUMN video2_url TEXT NOT NULL DEFAULT '';
ALTER TABLE days ADD COLUMN video3_url TEXT NOT NULL DEFAULT '';
ALTER TABLE days ADD COLUMN file_path  TEXT NOT NULL DEFAULT '';
ALTER TABLE days ADD COLUMN quiz_text  TEXT NOT NULL DEFAULT '';
